version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6

     steps:
       - checkout

       - restore_cache:
           key: dependencies-v1-{{ checksum "package-lock.json" }}

       - run:
           command: npm install

       - save_cache:
           key: dependencies-v1-{{ checksum "package-lock.json" }}
           paths:
             - node_modules

       - run:
           command: npm run lint

       - run:
           command: npm test

       - run:
           command: npm run build

experimental:
  notify:
    branches:
      only:
        - master
